# References: https://gist.github.com/michaelneu/2ca7987ef00fa3fbe4fd7b9c07834cc7
nginx:
  image: "nginx:latest"
  container_name: web-youtube-downloader
  volumes:
    - $PWD/youtube-downloader/public:/code:ro
    - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
    - $PWD/log:/var/log/nginx/
  ports:
    - 5000:80
  restart: always
